### PR TITLE
Bugfix/carousel

### LINKED ISSUE #1338: IE only: axa-carousel standalone not working correctly
if the component is embedded everything is ok.

Open up standalone the slides are not found.

### PR DESCRIPTION
**Pull request by danyball**
fixes #1338

### CODE REVIEW

File: src/components/10-atoms/carousel/index.js [hunk 1]
```diff
@@ -68,12 +68,30 @@ class AXACarousel extends InlineStyles {
   // private methods
 
   _getSlides(usedThis = this) {
-    // usedThis as a property to encapsulate for unit tests
-    const slots = usedThis // do not use this.shadowRoot because of IE
-      .querySelector('slot')
+    const slotsSelectedByShadowRootFiltered = usedThis.shadowRoot
+      .querySelector('.js-carousel__wrapper > slot')
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/index.js]: This has to be tested in IE. It probably works but we should make sure, because ShadyCss is messing with our structure.

File: src/components/10-atoms/carousel/unit.test.js [hunk 2]
```diff
@@ -40,23 +40,127 @@ describe('AXACarousel', () => {
...
+        querySelector: () => {},
+        shadowRoot: mockedShadowRoot,
+      };
+
+      AXACarousel.prototype._getSlides(mockedThis);
+
+      expect(mockedFilter).toHaveBeenCalled();
+    });
+
+    test('_getSlides() should get the elements and filter them (withOUT ShadowRoot)', () => {
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/unit.test.js]: Why is withOUT written with uppercase?

File: src/components/10-atoms/carousel/unit.test.js [hunk 3]
```diff
@@ -40,23 +40,127 @@ describe('AXACarousel', () => {
...
+      };
+
+      const slots = AXACarousel.prototype._getSlides(mockedThis);
+
+      expect(slots).toStrictEqual(expectedSlots);
+    });
+    test('_getSlides() should return elements selected without shadowRoot', () => {
+      const expectedSlots = ['element'];
+
+      const mockedThis = {
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/unit.test.js]: shortable too

File: src/components/10-atoms/carousel/unit.test.js [hunk 4]
```diff
@@ -40,23 +40,127 @@ describe('AXACarousel', () => {
...
+              return {
+                filter: () => {
+                  return expectedSlots;
+                },
+              };
+            },
+          };
+        },
+        shadowRoot: {
+          querySelector: () => {
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/unit.test.js]: shortable too

File: src/components/10-atoms/carousel/unit.test.js (hunk 2 above)
Comment (danyball) [reply src/components/10-atoms/carousel/unit.test.js]: To see that it is different to the test "with ShadowRoot"

Comment (danyball) [reply src/components/10-atoms/carousel/unit.test.js]: To see that it is different to the test "with ShadowRoot"

File: src/components/10-atoms/carousel/unit.test.js [hunk 5]
```diff
@@ -40,23 +40,127 @@ describe('AXACarousel', () => {
...
 
-      expect(mockedQuerySelector).toHaveBeenCalledWith('slot');
-      expect(mockedFilter).toHaveBeenCalled(); // filter is only called if assignedNodes is called too
+      expect(mockedFilter).toHaveBeenCalled();
+    });
+
+    test('_getSlides() should return elements selected by shadowRoot', () => {
+      const expectedSlots = ['element'];
+
+      const mockedThis = {
```
[the remark this answers is not in the document]
Comment (danyball) [reply src/components/10-atoms/carousel/unit.test.js]: Shortened is much harder to read

File: src/components/10-atoms/carousel/index.js (hunk 1 above)
Comment (danyball) [reply src/components/10-atoms/carousel/index.js]: This line of code do not work in IE. But i have a if and a comment at line 87-89.
