### PR TITLE
should fix reboot cascade issue

### LINKED ISSUE #457: CSS cascade/injection order broken
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

`reboot.scss` should never overwrite component CSS.

## Actual Behavior

CSS cascade is broken since merge of #454 

## Steps to Reproduce the Problem

1. `git co develop`
2. `npm run serve`
3. check icons positions and buttons

screen shot 2018-06-06 at 16 42 52
screen shot 2018-06-06 at 16 43 13
screen shot 2018-06-06 at 16 43 25

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #457 

Changes proposed in this pull request:

 - searches for last `<style>` node and append's components CSS after it.
 - fixes `<axa-link>` attaches it's styles twice
 - fixes memory size of caching which node's styles have been added. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [x] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/js/abstract/base-component-global.js [hunk 1]
```diff
@@ -23,15 +24,25 @@ export default class BaseComponentGlobal extends BaseComponent {
...
+    if (styles && !memory[styles]) {
+      let target = document.head;
+      const styleNode = document.createElement('style');
+      const styleText = document.createTextNode(styles);
+
+      styleNode.appendChild(styleText);
+      styleNode.setAttribute('data-c-name', nodeName.toLowerCase());
+
+      if (!styleTags) {
+        styleTags = document.getElementsByTagName('style');
```
Comment (AndyOGo) [inline src/js/abstract/base-component-global.js]: @LucaMele 
Since the result of `getElementsByTagName` is live, we can lazily query this just once.
Downside, this reference will remain forever until the browser window is closed...

https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName

Comment (AndyOGo) [reply src/js/abstract/base-component-global.js]: same is true for the `memory`, I guess it's easier to cache by it's `nodeName` only. Not the whole CSS

Comment (LucaMele) [reply src/js/abstract/base-component-global.js]: i think so yes

File: src/components/m-link/index.js [hunk 2]
```diff
@@ -15,8 +15,6 @@ class AXALink extends BaseComponentGlobal {
 
 wcdomready(() => {
   window.customElements.define(AXALink.tagName, AXALink);
-
-  BaseComponentGlobal.appendGlobalStyles(styles);
```
Comment (AndyOGo) [inline src/components/m-link/index.js]: That was redundant

**Comment by AndyOGo** [comment]
related https://github.com/axa-ch/aletheia/issues/178

File: src/js/abstract/base-component-global.js [hunk 3]
```diff
@@ -19,19 +20,33 @@ export default class BaseComponentGlobal extends BaseComponent {
...
+      // It's super important that each components CSS is evaluated after our reboot.css
+      // Especially regarding integration this should prevent breaking our cascade.
+      if (!styleTags) {
+        styleTags = document.getElementsByTagName('style');
       }
+
+      const { length } = styleTags;
+
+      if (length) {
+        target = styleTags[length - 1].parentNode;
```
Comment (AndyOGo) [inline src/js/abstract/base-component-global.js]: @LucaMele 
I see only one possible issue remaining.
What if the last stylesheet's tag `<style>` is after any custom element `<axa-foo>`.
Because our custom elements using global styles need their CSS before their usage.
So we may need special handling if such a case exists - keyword AEM Clientlibs and Design Importer?
