### PR TITLE
Dropdown selection and title issues

### LINKED ISSUE #833: Dropdown
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior
When I add dropdown as described below I expect title to be displayed and when I change value the new value to be seen.
Also there should be "value" attribute which I can use to pre-select the value from the items if the value exists in the list.

## Actual Behavior

Title is not displayed and whenever I change item only "1" is displayed.

## Steps to Reproduce the Problem
`<axa-dropdown  title="Please select" native items='[{"value":1,"name":1},{"value":2,"name":2},{"value":3,"name":3},{"value":4,"name":4},{"value":5,"name":5},{"value":6,"name":6},{"value":7,"name":7},{"value":8,"name":8},{"value":9,"name":9},{"value":10,"name":10},{"value":11,"name":11},{"value":12,"name":12},{"value":13,"name":13},{"value":14,"name":14},{"value":15,"name":15},{"value":16,"name":16},{"value":17,"name":17},{"value":18,"name":18},{"value":19,"name":19},{"value":20,"name":20},{"value":21,"name":21},{"value":22,"name":22},{"value":23,"name":23},{"value":24,"name":24},{"value":25,"name":25},{"value":26,"name":26},{"value":27,"name":27},{"value":28,"name":28},{"value":29,"name":29},{"value":30,"name":30},{"value":31,"name":31}]'>
</axa-dropdown>`

### PR DESCRIPTION
**Pull request by nakovskijosif**
Fixes #833.

Changes proposed in this pull request:
 - Fixed issue where numbers in list were not compared to string value.
- Added title to native dropdown which will be displayed only when there is no selected item.
- If there is a value set to the dropdown which has no corresponding value in the item list, title will be displayed if set.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/m-dropdown/_template.js [hunk 1]
```diff
@@ -3,6 +3,12 @@ import raw from 'nanohtml/raw';
 import classnames from 'classnames';
 
 const arrowIcon = '<axa-icon size="sm" icon="angle-bracket-down" classes="m-dropdown__icon"></axa-icon>';
+const getSelectedItem = (items) => {
+  if (!items || !Array.isArray(items) || !items.length) {
+    return null;
+  }
+  return items.filter(item => item.isSelected)[0];
+};
```
Comment (jackblackCH) [inline src/components/m-dropdown/_template.js]: Generally, we should keep code "together" in the controller (index.js) instead of moving it into the view (like the `getSelectedItem` function). Now parts of code are in the template and others are in the index.js. A view should only act as view and should not prepare nor manipulate data ( and If we had tests, it would even be harder to test in the view).

In this specific example, The `selectedItem` is already existing on line 160 in index.js, it may be enough to pass this prop down to the template and access it from there, no need to do figure out the selected item with another helper `(getSElectedItem)` again.

File: src/components/m-dropdown/_template.js [hunk 2]
```diff
@@ -3,6 +3,12 @@ import raw from 'nanohtml/raw';
 import classnames from 'classnames';
 
 const arrowIcon = '<axa-icon size="sm" icon="angle-bracket-down" classes="m-dropdown__icon"></axa-icon>';
+const getSelectedItem = (items) => {
+  if (!items || !Array.isArray(items) || !items.length) {
+    return null;
+  }
+  return items.filter(item => item.isSelected)[0];
```
Comment (MKaHead) [inline src/components/m-dropdown/_template.js]: if `return items.filter(item => item.isSelected)[0]` is undefined - I would recommend to return null
like that `return items.filter(item => item.isSelected)[0] || null` or a other implementation.
because in the render template you should do a  save type check like `getSelectedItem(items) === null`

File: src/components/m-dropdown/_template.js (hunk 1 above)
Comment (nakovskijosif) [reply src/components/m-dropdown/_template.js]: I agree. I'll update as soon as I can.

File: src/components/m-dropdown/_preview.html [hunk 3]
```diff
@@ -75,4 +75,7 @@ <h2>Native Dropdown Long list</h2>
     {"name": "The longer Item than the box", "value": "The longer Item than the box", "url": "#", "isSelected": false },
     {"name": "The longer Item than the box", "value": "The longer Item than the box", "url": "#", "isSelected": false }
   ]'
-></axa-dropdown>
\ No newline at end of file
+></axa-dropdown>
+<h2>Native Dropdown With Title</h2>
+<axa-dropdown native title="Please select" items='[{"value":1,"name":1},{"value":"","name":2},{"value":3,"name":3},{"value":4,"name":4},{"value":5,"name":5},{"value":6,"name":6},{"value":7,"name":7},{"value":8,"name":8},{"value":9,"name":9},{"value":10,"name":10},{"value":11,"name":11},{"value":12,"name":12},{"value":13,"name":13},{"value":14,"name":14},{"value":15,"name":15},{"value":16,"name":16},{"value":17,"name":17},{"value":18,"name":18},{"value":19,"name":19},{"value":20,"name":20},{"value":21,"name":21},{"value":22,"name":22},{"value":23,"name":23},{"value":24,"name":24},{"value":25,"name":25},{"value":26,"name":26},{"value":27,"name":27},{"value":28,"name":28},{"value":29,"name":29},{"value":30,"name":30},{"value":31,"name":31}]'>
```
Comment (MKaHead) [inline src/components/m-dropdown/_preview.html]: If `value` and `name` of a `item` can be number and string, then the PropTypes should be updated like that:
`items: PropTypes.arrayOf(PropTypes.shape({`
`     name: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),`
`     value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),`
`     ...`

Comment (nakovskijosif) [reply src/components/m-dropdown/_preview.html]: Done

File: src/components/m-dropdown/_template.js (hunk 1 above)
Comment (nakovskijosif) [reply src/components/m-dropdown/_template.js]: I removed this helper and added selectedItem as attribute.

File: src/components/m-dropdown/_template.js (hunk 2 above)
Comment (nakovskijosif) [reply src/components/m-dropdown/_template.js]: I removed this helper, but I return null in the duplicate helper and do type check.

File: src/components/m-dropdown/index.js [hunk 4]
```diff
@@ -214,6 +215,14 @@ class AXADropdown extends BaseComponentGlobal {
   get native() {
     return this.getAttribute('native');
   }
+
+  set selectedItem(value) {
+    this.setAttribute('selected-item', JSON.stringify(value));
+  }
+
+  get selectedItem() {
+    return JSON.parse(this.getAttribute('selected-item'));
```
Comment (LucaMele) [inline src/components/m-dropdown/index.js]: why setting this as prop? can it not just e a function or helper inside `index.js`?

Comment (nakovskijosif) [reply src/components/m-dropdown/index.js]: Well, I need info in `template.js` whether there is selected item or not. I had a function for it in `template.js` but it was suggested that I remove it and get that info from the `index.js`. 
I'm not sure which is the best way to do it, and I would appreciate your suggestion.

Comment (LucaMele) [reply src/components/m-dropdown/index.js]: i think is meant to just pass it down instead of calculating inside the template. Now we have a attribute that always changes and triggers a new-rendering. Can the funciton not just live in `index.js` and pass the filtered value with `get item()`? then in template u access it easly via wcNode

Comment (LucaMele) [reply src/components/m-dropdown/index.js]: if its not clear, we can have a quick call

Comment (nakovskijosif) [reply src/components/m-dropdown/index.js]: Thanks @LucaMele for the help. Requested changes implemented.
