### PR TITLE
Bugfix/1740 italian fix

### LINKED ISSUE #1740: Datepicker: "de-CH" locale enforcement for the date formatting
Chromium/Chrome browser incorrectly formats date to "20/4/2020" format for "'it-CH'" locale.
This is not good. It would be better to use "20.4.2020" date format throughout the AXA website. 
(discusses with Jonas on 21.4.2020)

(unsure now if this should be the case also for "en-CH" locale ?)

Copy from slack channel:

>Luca Mele
> Datepicker uses the native INTL API in the Browser. I guess Chromium just didn't 
>bother making dd.mm.yyyy for it-CH . Neverthen less, feel free to make an issue and we will get in 
>contact with the Chromium Community and find out more.
>
>We can also think for de-CH enforcement for the date and use other locals for the month name. 
>But please make an issue if you desire a solution for it.
>
> https://stackoverflow.com/questions/44973627/intl-datetimeformat-produces-wrong-format

### PR DESCRIPTION
**Pull request by danyball**
Fixes #1740 

# Done is when (DoD):
- [x] Modifications within components are reflected by tests.
- [x] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [x] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [x] The modifications are shortly added to CHANGELOG.md with the issue number.
- [x] The modifications still work in IE.
- [x] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

### CODE REVIEW

File: src/components/20-molecules/datepicker/utils/date.js [hunk 1]
```diff
@@ -77,9 +84,16 @@ const addLeadingZeroes = (rawNumber, numDigits) => {
...
-const parseLocalisedDateIfValid = (locale = 'en', inputValue = '') => {
-  if (!Intl.DateTimeFormat.supportedLocalesOf(locale).length) {
-    throw new Error(`locale not supported: ${locale}`);
+const parseLocalisedDateIfValid = (
+  inputLocale = LOCALE_DEFAULT,
+  inputValue = ''
+) => {
+  let locale = inputLocale;
+
+  if (!locale || !Intl.DateTimeFormat.supportedLocalesOf(locale).length) {
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/utils/date.js]: This looks complicated and cumbersome.

Suggestion: extract tests to named variables, like
`const unsupported = !Intl....` and `const missing = !locale;` and `const isSwissItalian = locale === 'it-CH';`

Then do a clean `locale = (missing || unsupported) ? LOCALE_DEFAULT : (isSwissItalian ? LOCALE_DE_CH : locale);`

File: src/components/20-molecules/datepicker/utils/date.js [hunk 2]
```diff
@@ -77,9 +84,16 @@ const addLeadingZeroes = (rawNumber, numDigits) => {
...
+    locale = LOCALE_DEFAULT;
+  } else if (locale.includes('it')) {
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/utils/date.js]: This is incorrect, because proper Italian locale does not format as de-CH! Test for full locale string, as suggested above.

**Review by markus-walther — CHANGES_REQUESTED** [review]
LGTM, some small beautifications and one bug correction.

File: src/components/20-molecules/datepicker/utils/date.js (hunk 2 above)
Comment (danyball) [reply src/components/20-molecules/datepicker/utils/date.js:95]: The default string for the attribute `local` was `en`. So i thought that both are valid, "en" and "en-GB" or "it" and "it-CH".

File: src/components/20-molecules/datepicker/utils/date.js (hunk 1 above)
Comment (danyball) [reply src/components/20-molecules/datepicker/utils/date.js]: This PR was not ready for review;) But thanks for reviewing! Named variables sounds quite good. Will change that. But i will not use this huge one-liner. This is more complicated than my if.

File: src/components/20-molecules/datepicker/utils/date.js [hunk 3]
```diff
@@ -77,9 +84,20 @@ const addLeadingZeroes = (rawNumber, numDigits) => {
...
+  let locale = inputLocale;
+  const localeUnsupported = () =>
+    !Intl.DateTimeFormat.supportedLocalesOf(locale).length;
+  const localeMissing = !locale;
+  const localeIsSwissItalian = locale === 'it-CH';
+
+  if (localeMissing || localeUnsupported()) {
+    locale = LOCALE_DEFAULT;
+  } else if (localeIsSwissItalian) {
+    locale = LOCALE_DE_CH; // change locale to de-CH because of wrong date formatting of browsers (#1740)
```
Comment (01231) [inline src/components/20-molecules/datepicker/utils/date.js:100]: very helpful comment👍🏼

File: src/components/20-molecules/datepicker/story.js [hunk 4]
```diff
@@ -14,9 +14,12 @@ import Changelog from './CHANGELOG.md';
 
 const localeOptions = {
   'de-CH': 'de-CH',
+  'it-CH': 'it-CH',
+  'fr-CH': 'fr-CH',
+  'en-CH': 'en-CH',
   'en-GB': 'en-GB',
   'it-IT': 'it-IT',
-  'fr-CH': 'fr-CH',
+  'invalid/ unsupported': 'ff-XX',
```
Comment (01231) [inline src/components/20-molecules/datepicker/story.js]: What is the use of this? If this is not something trivial i would recommend to write a comment.

**Review by 01231 — DISMISSED** [review]
Good job!

File: src/components/20-molecules/datepicker/story.js (hunk 4 above)
Comment (danyball) [reply src/components/20-molecules/datepicker/story.js]: To show the default language fallback scenario. Will add a comment

**Review by 01231 — APPROVED** [review]

**Comment by MarekLacoAXA** [comment]
Unsure how the italian fix is supposed to work, but in my environment, with datepicker 7.0.6, in Chrome browser, I still see slashes as separators:

The dots appear only when I choose the selected date again.

image

**Comment by MarekLacoAXA** [comment]
I uderstand now, please disregard.
