### PR TITLE
imporve release script

### LINKED ISSUE #409: Add hotfix option to release script
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

We want to be able to immediatly release **hotfixes** in a consistent manner.
Git fast-forward should be disabled to allow for hotfix releases.

As we have transformed the axa-ch user on npm to a axa-ch group, we need to add the `--scope` flag on the npm publish

## Actual Behavior

We can't release hotfix by script atm and the git fast-forward thing is not fixed.

## Steps to Reproduce the Problem

https://github.com/axa-ch/patterns-library/wiki/Crafting-a-release#release-hotfix

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #409 

Changes proposed in this pull request:

 - adds hotfix option

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [x] I have made corresponding changes to the documentation
 - [x] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: stack/tasks/release.js [hunk 1]
```diff
@@ -165,60 +199,109 @@ const confirmedRelease = (type, version) => {
     return;
   }
 
-  waterfall([
-    (callback) => {
-      exec(`git checkout ${developTrunk} && git pull && git checkout -b release-tmp`, handleSuccess(callback, () => {
-        console.log(chalk.cyan(outdent`
+  let releaseSteps;
+
+  if (type === HOTFIX) {
```
Comment (LucaMele) [inline stack/tasks/release.js]: i would externalise common funcs and reuse them

Comment (AndyOGo) [reply stack/tasks/release.js]: you `isHotfix`? Thougt so too
