### PR TITLE
Change React-wrapper for Boolean props and fix checkbox as a result

### LINKED ISSUE #1761: Checkbox controlled-mode not working if initial checked property is false
Version: "@axa-ch/checkbox": "^4.0.1"

When initial checked property is false checkbox does not enter controlled-mode.

Reproduction link:
https://codesandbox.io/s/practical-leaf-lc0gs

### LINKED ISSUE #1772: IE: axa-radio "noGap" not working correctly
Reported by "Nick Rascher" over Slack. 

Open this page with IE11 (**React** demo. VanillaJS demo is working!):

https://patterns.axa.ch/?path=/story/components-atoms-radio-react-demos--controlled-component-react-ified-radio-button

There is a gap between buttons:
image

There's a margin at the first button. The CSS rule is not working?
image

### PR DESCRIPTION
**Pull request by markus-walther**
Fixes #1761.
fixes #1772 

This needs thorough thinking and reviewing, since it changes the behaviour for **all** Boolean properties under React.

### CODE REVIEW

File: src/utils/with-react.js [hunk 1]
```diff
@@ -132,11 +132,8 @@ const distributeProperties = (properties, componentClass) => {
       case Array:
       case Object:
       case Function:
-        map = props;
-        break;
       case Boolean:
-        map = attrs;
-        value = value ? '' : null; // ''/null: canonicalize Boolean values s.t. val(...) sets or removes the attribute
+        map = props;
```
Comment (danyball) [inline src/utils/with-react.js:136]: No need for a switch-case anymore. A simple if should be enough?!

**Review by danyball — COMMENTED** [review]
Can you add a knob or a demo for that?

**Review by LucaMele — APPROVED** [review]
LGTM

**Comment by markus-walther** [comment]
> Can you add a knob or a demo for that?

Difficult, since it affects the internal 'plumbing' only, its infrastructure code.

File: src/utils/with-react.js (hunk 1 above)
Comment (markus-walther) [reply src/utils/with-react.js:136]: As discussed bilaterally, this has its own downsides (repeated type === ...), so I prefer to keep it as-is.
