### PR TITLE
fix(inner-svg): imported twice

### LINKED ISSUE #751: React demo broken
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

Demo Page should be visible.

## Actual Behavior

Demo Page shows almost nothing.

## Steps to Reproduce the Problem

1. go to https://axa-ch.github.io/patterns-library/react.html

screen shot 2018-12-07 at 08 46 10

## Specifications

 - Browser: All (Chrome)
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:
 
## Failure Logs

> TypeError: can't redefine non-configurable property "innerHTML"

screen shot 2018-12-07 at 08 48 56

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #751 

Changes proposed in this pull request:

 - fixes `innerSVG` polyfill imported twice

This happens because we still bundle same modules more than once...

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/demos/todomvc/todos.jsx [hunk 1]
```diff
@@ -4,7 +4,10 @@ import TodosList from './todos-list';
 import TodoFooter from './todo-footer';
 import { ALL_TODOS, ACTIVE_TODOS, COMPLETED_TODOS } from './utils';
 
-import { AXADatepicker } from '../../js/react-exports';
```
Comment (AndyOGo) [inline src/demos/todomvc/todos.jsx]: Since we added polyfill import to `index.js` and `react-exports`, they land twice on the page and innerSVG prolyfill throughs upon second attempt...
