### PR TITLE
bugfix icon root node no class

### LINKED ISSUE #593: Icon root node is not styled
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

We should fully control the size and stlye of it's root node `<axa-icon>`

## Actual Behavior

`<axa-icon>` hasn't any class nor styles. By default it's rendered as an inline element, so it's inherited `line-height`, `font-size` etc. properties affects how it is displayed and sized.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

### LINKED ISSUE #596: Root class lost after parent updates
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

The `class` attribute should not get lost after parent component updates.
Thanks to @LucaMele for finding it.

## Actual Behavior

The `class` of the root node is lost and `_isConnected` is even `false` 😕 
Looks like it is happening after initial rendering within the cloning phase 🤔 

screen shot 2018-10-08 at 15 20 54

## Steps to Reproduce the Problem

root-class-lost-on-parent-change

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

### PR DESCRIPTION
**Pull request by AndyOGo**
Improves #593 and fixes #596 

Changes proposed in this pull request:

 - just adds `.a-icon__root` class
 - fixed DOM moprhing breaks classes of child custom elements after parent updates

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/a-icon/index.js [hunk 1]
```diff
@@ -19,6 +19,10 @@ class AXAIcon extends BaseComponentGlobal {
   constructor() {
     super({ styles, template });
   }
+
+  didRenderCallback() {
+    this.className = 'a-icon';
```
Comment (AndyOGo) [inline src/components/a-icon/index.js]: this is key

File: src/components/a-icon/index.scss [hunk 2]
```diff
@@ -1,9 +1,11 @@
-.a-icon {
+a-icon {}
```
Comment (AndyOGo) [inline src/components/a-icon/index.scss]: Not sure if we want to provide some default styles 🤔

File: src/components/a-icon/index.js [hunk 3]
```diff
@@ -19,6 +19,10 @@ class AXAIcon extends BaseComponentGlobal {
   constructor() {
     super({ styles, template });
   }
+
+  didRenderCallback() {
+    this.className = 'a-icon__root';
```
Comment (AndyOGo) [inline src/components/a-icon/index.js]: @LucaMele 
Just added this class, to be selectable by CSS and not to break any existing functionality

Comment (AndyOGo) [reply src/components/a-icon/index.js]: Though there might be other issues to be fixed regarding this...

File: src/js/abstract/utils/morph.js [hunk 4]
```diff
@@ -9,6 +9,12 @@ export default morph;
 function morph(newNode, oldNode) {
   const { nodeType, nodeName } = newNode;
 
+  // IMPORTANT: cloned custom elements aren't connected
+  // so just skip them - they will morph themselves upon connection
+  if (oldNode.skipChildren && oldNode.skipChildren()) {
```
Comment (AndyOGo) [inline src/js/abstract/utils/morph.js]: I tested it in chrome including the react demo:)
