### PR TITLE
Bugfix/with react invalid constructor

### LINKED ISSUE #430: with-react only avaiable as src. should be transpiled for dist
## Are you reporting a bug or a feature?

 - [ ] Bug
 - [x] Feature

## Expected Behavior

with-react only avaiable as src. should be transpiled for dist

### LINKED ISSUE #445: TypeError: WebComponent is not a constructor
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

`withReact` should wrap any WebComponent without any complaints.

## Actual Behavior

**TypeError:** `WebComponent is not a constructor` is thrown.

## Steps to Reproduce the Problem

I assume this is caused by running React before the used CustomElement is registered within the [CustomElementRegistry API](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry).

The other issue is, that we call the custom-element's `constructor` directly instead of using `document.createElement()` - mainly because we don't have it's `tagName` available.

So to fix this, I suppose that we add the `tagName` as static properties to all constructors.

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #445 
Fixes #430 

Changes proposed in this pull request:

 - add static `tagName` to each custom element
 - refactored `create-a-m-o.js` script accordingly
 - refactored `withReact` to stop instantiating custom elements, but rather use the new static `tagName` property
- refactored react Demo to drop `wcdomready` and use `<axa-checkbox />`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [x] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AndyOGo** [comment]
@LucaMele 
@pavestru 
I started adding `<axa-checkbox />` to our react demo - changing props from outside works, onchange event needs to be handled still...

with-react-checkbox

File: stack/tasks/create-a-m-o.js [hunk 1]
```diff
@@ -70,6 +70,8 @@ const writeIndexJs = (path, _name) => {
       import wcdomready from '../../js/wcdomready';
 
       class ${className} extends BaseComponentGlobal {
+        static tagName = 'axa-${_name}'
```
Comment (LucaMele) [inline stack/tasks/create-a-m-o.js]: welldone :)

**Comment by AndyOGo** [comment]
and yet another build issue #448
