### PR TITLE
Add fix to reset rest css that can be used on consumers website

### LINKED ISSUE #1021: Button eventuell broken
dede

type='button'

### PR DESCRIPTION
**Pull request by LucaMele**
Reset common reset.css/normalise.css out there.

they add styling like so: `[type="button"]` and add appearance to 'button'

fixes #1021

### CODE REVIEW

File: src/components/10-atoms/button-link/index.js [hunk 1]
```diff
@@ -43,6 +43,15 @@ class AXAButtonLink extends LitElement {
     this.onClick = () => {};
   }
 
+  firstUpdated() {
+    const { style } = this;
```
Comment (raphaellueckl) [inline src/components/10-atoms/button-link/index.js]: Are you sure this works? Isn't it `this.styles`?

Comment (raphaellueckl) [reply src/components/10-atoms/button-link/index.js]: plural
