### PR TITLE
Bugfix/react demo broken locally

### LINKED ISSUE #729: React demo page broken locally
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

React demo page should work at all stages

## Actual Behavior

At least is broken locally since #695 

## Steps to Reproduce the Problem

1. `rm -r node_modules/`
2. `npm i && npm run serve`
3. go to http://localhost:3000/react.html

> all-demos.js | 404 | script | react.html | 249 B | 17 ms

screen shot 2018-12-04 at 12 36 43

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #729 
Changes proposed in this pull request:

 - reenabled demos
 - remove old `@webcomponents` polyfill exclusions

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: stack/tasks/bundle-demos.js [hunk 1]
```diff
@@ -28,7 +28,6 @@ async function buildComponents() {
       ENV === constants.ENV.PROD ? uglify() : () => {},
       commonjs({
         include: 'node_modules/**',
-        exclude: ['node_modules/@webcomponents/webcomponentsjs/**'],
```
Comment (LucaMele) [inline stack/tasks/bundle-demos.js]: nice catch
