### PR TITLE
Feature/fix icon performance

### LINKED ISSUE #1995: Storybook is very slow - especially in a local environment
## Current Behavior

Working locally is a pain. Reloading the page takes forever, and when opening the icon component story everything freezes
## Expected Behavior
The page should reload fast and the icons story should not freeze anymore.

## Steps to Reproduce

1. Reload page when working locally
or
1. Open icons story

## Possible Solution

Adjust how icons are displayed/loaded?

### PR DESCRIPTION
**Pull request by raphaellueckl**
Fixes #1995

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Modifications still work in IE.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.

### CODE REVIEW

**Review by danyball — CHANGES_REQUESTED** [review]
Pls remove `Overwrite Colors:` button - users can change that via Knobs. Other change LGTM.

**Review by 01231 — CHANGES_REQUESTED** [review]
Would suggest that icons and images start at the same level:
Screenshot 2020-10-28 at 08 39 37

Name should be fully visible on hover. Otherwise the user can't use the icon because he doesn't knows the name.
Screenshot 2020-10-28 at 08 40 54

**Review by 01231 — CHANGES_REQUESTED** [review]
Icons column is 260px wide and images column 276px. I would expect, that both columns use equal space.

Screenshot 2020-10-28 at 08 55 23

-------------------------

Screenshot 2020-10-28 at 08 55 31

File: src/components/00-materials/story.js [hunk 1]
```diff
@@ -194,8 +264,15 @@ export const IconsAndImages = () => {
...
 
-      .item-name {
+      .materials__asset-name {
         margin-left: 5px;
+        margin-right: 10px;
+        width: 210px;
+      }
+
+      .materials__asset-name > p {
+        text-overflow: ellipsis;
```
Comment (danyball) [inline src/components/00-materials/story.js:267]: The only purpose for the story is to show the name of the icons in my opinion :). I would never ellippsis them. So that developers can copy-paste the names.

We have enough space on the right. Maybe just not set a width to this row (at line 270)

File: src/components/00-materials/story.js [hunk 2]
```diff
@@ -194,8 +264,15 @@ export const IconsAndImages = () => {
         margin: 20px 0;
       }
 
-      .item-name {
+      .materials__asset-name {
         margin-left: 5px;
+        margin-right: 10px;
+        width: 210px;
```
Comment (danyball) [inline src/components/00-materials/story.js]: We have enough space on the right. Maybe just not set a width to this row (at line 270)

**Review by danyball — CHANGES_REQUESTED** [review]

File: src/components/00-materials/story.js (hunk 1 above)
Comment (raphaellueckl) [reply src/components/00-materials/story.js:267]: But what if google decides to do this?

`super-duper-ultra-long-and-weird-svg-name-that-does-take-a-lot-of-space.svg`?

There are some super long names and I think, with autocomplete people could still find the icon when they import. The only other solution I see here is to increase the width of the text.

File: src/components/00-materials/story.js (hunk 2 above)
Comment (raphaellueckl) [reply src/components/00-materials/story.js]: Yeah, this is a good idea I think

File: src/components/00-materials/story.js (hunk 1 above)
Comment (raphaellueckl) [reply src/components/00-materials/story.js:267]: I made a compromise: Increased the max-width of the text significantly.

**Review by danyball — DISMISSED** [review]

**Review by 01231 — CHANGES_REQUESTED** [review]
Please set "Note: ..." on a new line like it is on dev.
Is:
Screenshot 2020-10-28 at 15 14 13

Should:
Screenshot 2020-10-28 at 15 12 14

**Review by 01231 — APPROVED** [review]
LGTM
