### PR TITLE
Bugfix/testimonials

### LINKED ISSUE #1346: Testimonials: IE only: show-all-inline without margins
the author should have more space to the text above:

image

### LINKED ISSUE #1350: Testimonials: showallinline=false not working
if attribute is set to false, component shows all inline. Thats wrong. The if should test false/true

### PR DESCRIPTION
**Pull request by danyball**
fixes #1350 
fixes #1346

### CODE REVIEW

File: src/components/30-organisms/testimonials/index.js [hunk 1]
```diff
@@ -55,7 +57,7 @@ class AXATestimonials extends InlineStyles {
       title,
       subtitle,
       showallinline,
-      autorotatetime,
+      autorotatetime = DEFAULT_AUTOROTATETIME,
```
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/index.js]: Why a second time here?

File: src/components/10-atoms/carousel/README.md [hunk 2]
```diff
@@ -33,7 +33,7 @@ export default AXACarouselReact;
 ```
 
 ```js
-<AXACarouselReact keysenabled="true">
+<AXACarouselReact keysenabled="">
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/README.md]: keysenabled as an empty string? why?

Comment (danyball) [reply src/components/10-atoms/carousel/README.md]: true/false here is not correct. i am checking if the attribute is set, and if not, the result will be false. But keysenabled="false" had true as the result.

Comment (raphaellueckl) [reply src/components/10-atoms/carousel/README.md]: BBut if this only acts as a boolean, you could instead write just `keysenables` without an empty value attached to it.

File: src/components/10-atoms/carousel/README.md [hunk 3]
```diff
@@ -53,7 +53,7 @@ Import the carousel-defining script and use a carousel like this:
     <title>Your awesome title</title>
   </head>
   <body>
-    <axa-carousel keysenabled="true">
+    <axa-carousel keysenabled="">
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/README.md:56]: Why empty string here?

File: src/components/10-atoms/carousel/README.md [hunk 4]
```diff
@@ -13,7 +13,7 @@ npm install @axa-ch/carousel
 ```js
 import 'src/components/10-atoms/carousel/lib/index';
 
-<axa-carousel keysenabled="true">
+<axa-carousel keysenabled="">
```
Comment (raphaellueckl) [inline src/components/10-atoms/carousel/README.md:16]: Why empty string here?

File: src/components/30-organisms/testimonials/README.md [hunk 5]
```diff
@@ -14,12 +14,9 @@ npm install @axa-ch/testimonials
 import '@axa-ch/testimonials';
 
 <axa-testimonials
-  autorotatetime="1000"
-  autorotatedisabled="false"
-  keysenabled="true"
-  showallinline="false"
   title="The main title"
   subtitle="This is the subtitle"
+  keysenabled=""
```
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/README.md]: Why empty string here?

File: src/components/30-organisms/testimonials/README.md [hunk 6]
```diff
@@ -74,12 +68,9 @@ Import the testimonials-defining script and use a testimonials like this:
   </head>
   <body>
     <axa-testimonials
-      autorotatetime="1000"
-      autorotatedisabled="false"
-      keysenabled="true"
-      showallinline="false"
       title="The main title"
       subtitle="This is the subtitle"
+      keysenabled=""
```
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/README.md:53]: Why empty string here?

Comment (danyball) [reply src/components/30-organisms/testimonials/README.md:53]: This is just a variation. All these possibilities are correct:

> `Correct would be either <div hidden> or <div hidden=""> or <div hidden="hidden"> or case-insensitive and single quotes/unquoted variations of any of them.`

Luca said: for html examples set `=""`and for react examples just the attribute.

File: src/components/10-atoms/carousel/index.js [hunk 7]
```diff
@@ -155,7 +155,8 @@ class AXACarousel extends InlineStyles {
   // AutoRotate:
 
   _startAutoRotate() {
-    if (!this.autorotatedisabled) {
+    // eslint-disable-next-line no-restricted-globals
+    if (!this.autorotatedisabled && !!this.autorotatetime === true && !isNaN(this.autorotatetime)) {
```
Comment (01231) [inline src/components/10-atoms/carousel/index.js:177]: if `this.autorotatetime = true` it would pass this conditional statement

Comment (01231) [reply src/components/10-atoms/carousel/index.js:177]: `!!true === true` && `!isNaN(true) === true`

File: src/components/30-organisms/testimonials/package.json [hunk 8]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@axa-ch/testimonials",
-  "version": "0.0.1-alpha.0",
+  "version": "1.0.0",
```
Comment (01231) [inline src/components/30-organisms/testimonials/package.json:3]: shouldn't we change version number after a release?

File: src/components/10-atoms/carousel/README.md [hunk 9]
```diff
@@ -13,7 +13,7 @@ npm install @axa-ch/carousel
 ```js
```
Comment (01231) [inline src/components/10-atoms/carousel/README.md:13]: some general comment: in file `index.react.d.ts` of testimonials you forgot to delete row 3 (`type Variant = 'foo' | 'bar';`)

File: src/components/10-atoms/carousel/index.js (hunk 7 above)
Comment (danyball) [reply src/components/10-atoms/carousel/index.js:177]: yes, it should pass if autorotatetime is a number but NOT an emtpy string "" -> do you know a better solution?

File: src/components/30-organisms/testimonials/package.json (hunk 8 above)
Comment (danyball) [reply src/components/30-organisms/testimonials/package.json:3]: Because lerna manage the versions? I dont want to forget to set version to 1.0 at release time - so i manually set it. But youre right... not that nice here.

File: src/components/30-organisms/testimonials/README.md [hunk 10]
```diff
@@ -44,17 +21,14 @@ export default AXATestimonialsReact;
...
-  showallinline="false"
   title="The main title"
   subtitle="This is the subtitle"
+  keysenabled
 >
   <span>first slide</span>
   <div>
     <span>second slide</span>
-    <span class="author">Andrew Jackson, Advocate</span>
+    <span className="author">Andrew Jackson, Advocate</span>
```
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/README.md]: Use a prefix here. @LucaMele We also wanted to discuss what kind of classes we give child elements, if we even should rely on classes. AFAIR in child css we need to reference the tags. Dani can tell you abbout the discussion tomorrow.

File: src/components/30-organisms/testimonials/story.js [hunk 11]
```diff
@@ -45,25 +45,28 @@ story.add('Testimonials', () => {
         >
         <span class="author">Andrew Jackson, Advocate</span>
       </div>
-      <div>
+      <div class="showallinline_ie_bugfix">
```
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/story.js]: As discusses, this shouldn't have a name like this. @LucaMele  Maybe you can take a look at the bug dani is workarounding here.

File: src/components/30-organisms/testimonials/README.md (hunk 10 above)
Comment (LucaMele) [reply src/components/30-organisms/testimonials/README.md]: @danyball please use prefix and BEM always for classes. Therefore here something like: `o-testimonials__author` if is an organism or `m-testimonials__author`.

Other option is to set a attribute, which i dont like that much

File: src/components/30-organisms/testimonials/child.scss [hunk 12]
```diff
@@ -1,7 +1,7 @@
 @import '../../10-atoms/carousel/child';
 
 axa-testimonials {
-  span.author{
+  .author{
```
Comment (LucaMele) [inline src/components/30-organisms/testimonials/child.scss]: dtto classname is too generic

File: src/components/30-organisms/testimonials/index.js [hunk 13]
```diff
@@ -38,8 +38,8 @@ class AXATestimonials extends InlineStyles {
     super();
 
     // default values props
-    this.title = '';
-    this.subtitle = '';
+    this.title = null;
```
Comment (LucaMele) [inline src/components/30-organisms/testimonials/index.js]: Why from type String to Type Object? I would revert this change. `title` and `subtitle` are set as strings in the props so please use as default value empty string and not an object.

File: src/components/30-organisms/testimonials/story.js [hunk 14]
```diff
@@ -36,7 +36,7 @@ story.add('Testimonials', () => {
       title="${title}"
       subtitle="${subtitle}"
     >
-     <div>
+      <div class="showallinline_ie_bugfix">
```
Comment (LucaMele) [inline src/components/30-organisms/testimonials/story.js]: dtto, name does not follow our css rules: `o-testimonials__showallinline__ie__bugfix`

File: src/components/30-organisms/testimonials/story.js (hunk 11 above)
Comment (LucaMele) [reply src/components/30-organisms/testimonials/story.js]: dtto, name does not follow our css rules: `o-testimonials__showallinline__ie__bugfix`

File: src/components/30-organisms/testimonials/react/story.jsx [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+          sorted in 10 minutes after 3 weeks of phone calls. Very helpful once I
+          got through to the correct person but I was constantly being
+          transferred from person to person, in the end I called into my local
+          axa once in the city and got sorted in 10 minutes after 3 weeks of
+          phone calls. Very helpful once I got through to the correct person but
+          I was constantly being transferred from person to person, in the end I
+          called into my local axa once in the city and got sorted in 10 minutes
+          after 3 weeks of phone calls.
+        </span>
+        <span className="author">Andrew Müller, Advocate</span>
```
Comment (LucaMele) [inline src/components/30-organisms/testimonials/react/story.jsx]: @danyball here still not BEM class

File: src/components/30-organisms/testimonials/README.md (hunk 10 above)
Comment (raphaellueckl) [inline src/components/30-organisms/testimonials/README.md]: Still old classname
