### PR TITLE
fix(device-state): content undefined type error

### LINKED ISSUE #742: Device State TypeError: undefined is not an object (evaluating 'content.replace')
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Steps to Reproduce the Problem

1. at least Safari

screen shot 2018-12-05 at 19 27 34

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:
 
## Failure Logs

> TypeError: undefined is not an object (evaluating 'content.replace')

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #742 

Changes proposed in this pull request:

 -
 -
 -

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/js/device-state.js [hunk 1]
```diff
@@ -84,11 +93,16 @@ export default class DeviceStateObserver {
   }
 
   getDeviceState(content) {
+    if (typeof content !== 'string') {
```
Comment (AndyOGo) [inline src/js/device-state.js]: Seems this bug was introduce by the r[efactoring 3 months ago](https://github.com/axa-ch/patterns-library/commit/61d7cafafdb43beb64f5326343e6aef215ee1e23) 🤔 
May I ask to restore the original script?
