### PR TITLE
2409 some flaky datepicker tests

### LINKED ISSUE #2409: Some flaky datepicker tests
Please only report technical bugs. Clarify design issues in the slack channel #ux-ui-support.

Datepicker tests running sometimes in errors.

## Expected Behavior
Tests should bring always the same result.

## Current Behavior
When tests are executed, sometimes they bring an error, sometimes not (without any changes).

## Steps to Reproduce

1. use a M1 Max 64 GB Macbook
2. run Tests multiple times
3.
4.

## Context (Environment)

Apple M1 Max, 64 GB, MacOS 13.1

## Possible Solution

Optimize Test

### PR DESCRIPTION
**Pull request by thomas-krueger-axa**
Fixes #

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

**Review by stefan-17367837 — DISMISSED** [review]

File: src/components/20-molecules/datepicker/e2e.js [hunk 1]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
         '29.02.2020 (of 1 submittable elements)'
       );
     });
+
+    test('should just add years of a given range', async ({ page }) => {
+      await page.goto(fixtureURL('components-datepicker--datepicker'));
+
+      const datepicker = await page.locator('axa-datepicker');
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js]: It would arguably be more stable to use the selector `[data-test-id="datepicker"]`, since that is explicitly provided for testing.

File: src/components/20-molecules/datepicker/e2e.js [hunk 2]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
...
+      await datepicker.evaluate(node => {
+        node.allowedyears = ['1999-2000'];
+      });
+
+      const datepickerYearDropdown = await page.locator(
+        'axa-datepicker .js-datepicker__dropdown-year'
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js]: see above, same applies here.

File: src/components/20-molecules/datepicker/e2e.js [hunk 3]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
...
+      );
+      const itemsString = await datepickerYearDropdown.getAttribute('items');
+
+      const itemsArray = JSON.parse(itemsString);
+
+      expect(itemsArray.length).toBe(2);
+      expect(itemsString).toContain('"value":"1999"');
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js]: This was straightforwardly copied from the old Testcafe test. But now that we have an opportunity to redo it, we can do better: use `itemsArray[0]` and `itemsArray[1]` and test (toBe) for the exact values at the exact positions!

File: src/components/20-molecules/datepicker/e2e.js [hunk 4]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
...
+      expect(itemsString).not.toContain('"value":"2020"');
+    });
+
+    test('should fire the right events', async ({ page }) => {
+      await page.goto(
+        fixtureURL('examples-datepicker-pure-html--with-onchange-handler')
+      );
+
+      const datepickerForm = await page.locator(
+        `axa-datepicker[data-test-id="datepicker-onchange"]`
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js]: AFAIK data-test-id values are never reused, so you can simplify this selector by dropping the `axa-datepicker` part.

File: src/components/20-molecules/datepicker/e2e.js [hunk 5]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
...
+      );
+      expect(datepickerForm).toBeTruthy();
+
+      await page.locator('.js-datepicker__input-button').click();
+
+      await page
+        .locator('.m-datepicker__calendar-current-month[data-day="16"]')
+        .click();
+      expect(await page.locator('.event-log').inputValue()).toContain(
+        `{"name":"date","value":"16.2.2020"}\n\n`
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js:102]: why test for double newlines, what purpose does this serve?

File: src/components/20-molecules/datepicker/e2e.js [hunk 6]
```diff
@@ -36,5 +36,55 @@ test.describe('datepicker', () => {
...
+      );
+
+      await page
+        .locator(
+          'axa-datepicker[data-test-id="datepicker-onchange"] .js-datepicker__input'
+        )
+        .fill('29.2.1976');
+      expect(await page.locator('.event-log').inputValue()).toContain(
+        `\n\n{"name":"date","value":"29.2.1976"}\n\n`
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js]: why test for double newlines, what purpose does this serve?

File: src/components/30-organisms/footer/e2e.js [hunk 7]
```diff
@@ -6,11 +6,11 @@ test.describe('footer', () => {
...
 
     const footerBoundingBoxDefault = await page.locator('footer').boundingBox();
-    expect(footerBoundingBoxDefault.height).toBe(314.6875);
+    const initialHeight = footerBoundingBoxDefault.height;
 
     await page.locator('#footerTestButton').click();
 
     const footerBoundingBoxAfter = await page.locator('footer').boundingBox();
-    expect(footerBoundingBoxAfter.height).toBe(278.75);
+    expect(footerBoundingBoxAfter.height).toBeLessThan(initialHeight);
```
Comment (markus-walther) [inline src/components/30-organisms/footer/e2e.js]: Good! Only thing I asked myself is whether to prescribe a minimum offset for less-than (suppose it is half a pixel less...). Think about it.

**Review by markus-walther — CHANGES_REQUESTED** [review]
Dear Thomas,

this is quite some good work! I see we are quickly getting another Playwright wizard ;-)

I found a few issues to address.

But the biggest issue I mention here: lack of comments.

I strongly urge you to comment most lines of code. Preface the code with the _intent_ of what you aim to do in the line below, using good English.

The test for good commenting is this: does a coherent English story remain when I delete all code?

Cheers, Markus

**Review by amir-ag — DISMISSED** [review]

File: src/components/20-molecules/datepicker/e2e.js [hunk 8]
```diff
@@ -3,38 +3,115 @@ import { fixtureURL } from '../../../utils/e2e-helpers';
...
+      // Click on the datepicker input button
+      await page.locator('.js-datepicker__input-button').click();
+
+      // Click on the 16th day of the current month
+      await page
+        .locator('.m-datepicker__calendar-current-month[data-day="16"]')
+        .click();
+
+      // The date object is separated by a newline character in the event log
+      // Therefore, we need to check for the presence of this character to ensure that we are matching the correct date
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js:100]: But we are testing for **2** successive newlines. So, your comment is incomplete, only half of the story. Once you explain that, it's good.

File: src/components/20-molecules/datepicker/e2e.js [hunk 9]
```diff
@@ -3,38 +3,115 @@ import { fixtureURL } from '../../../utils/e2e-helpers';
...
+      expect(await page.locator('.event-log').inputValue()).toContain(
+        `{"name":"date","value":"16.2.2020"}\n\n`
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js:102]: ditto, see above.

File: src/components/20-molecules/datepicker/ui.test.js [hunk 10]
```diff
@@ -710,7 +690,7 @@ test('should allow year ranges', async t => {
     return JSON.stringify(domNode[property]);
   });
 
-  await t.setTestSpeed(0.5);
+  await t.setTestSpeed(0.25);
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/ui.test.js:693]: didn't we say this fiddling with test speed is a sign that this particular test, too, should be rewritten in PlayWright?

File: src/components/30-organisms/footer/e2e.js [hunk 11]
```diff
@@ -1,16 +1,22 @@
...
 
+    // Save the initial height of the footer element
     const footerBoundingBoxDefault = await page.locator('footer').boundingBox();
-    expect(footerBoundingBoxDefault.height).toBe(314.6875);
+    const initialHeight = footerBoundingBoxDefault.height;
 
+    // Click the button that changes the height of the footer element
     await page.locator('#footerTestButton').click();
 
+    // Measure the new height of the footer element and check if it is at least 20 pixels smaller than the initial height
```
Comment (markus-walther) [inline src/components/30-organisms/footer/e2e.js:18]: OK, but why 20px? Magic constants always need explaining. What you really want to say here that it is smaller by a 'comfortable margin', which you chose to be 20px. If you say this, then it's fine.

**Review by markus-walther — CHANGES_REQUESTED** [review]
Hi Thomas,

good work! Some small issues remain in my view, and an open question regarding whether one more test should be ported over to PlayWright.

Cheers, Markus

File: src/components/20-molecules/datepicker/ui.test.js (hunk 10 above)
Comment (thomas-krueger-axa) [reply src/components/20-molecules/datepicker/ui.test.js:693]: Yes, this is correct. But i think for the moment it is too complex to migrate (this single test). Since we have special functions for the testcafe tests. I think it would make more sense to migrate all tests for this component in one step.
If you think different, let us discuss about :-)

Comment (markus-walther) [reply src/components/20-molecules/datepicker/ui.test.js:693]: I beg to differ here. This particular test (lines 684-726) is not too complex, since 2 of 3 helper functions are defined inside the test, hence can easily be ported in isolation for that test only. They are client functions, i.e. run in the browser, which makes their function body carry over to PlayWright 1:1. Lines 702-706 to open the calendar use an outside helper function - these lines should be redone idiomatic Playwright style. Let's do it!

**Review by markus-walther — CHANGES_REQUESTED** [review]
Hi Thomas,

I think you should do the Playwright test that you argued is too complex. And I still cannot map your comment to the two newlines - you either need to show the log format in your comment or explain the number two better.

Cheers, Markus

**Comment by thomas-krueger-axa** [comment]
> 

As we told about, i've created a new ticket for the migration #2426

File: src/components/20-molecules/datepicker/e2e.js [hunk 12]
```diff
@@ -3,38 +3,115 @@ import { fixtureURL } from '../../../utils/e2e-helpers';
...
+
+      // Click on the datepicker input button
+      await page.locator('.js-datepicker__input-button').click();
+
+      // Click on the 16th day of the current month
+      await page
+        .locator('.m-datepicker__calendar-current-month[data-day="16"]')
+        .click();
+
+      // The date object is separated by a newline character in the event log (for better readability)
```
Comment (markus-walther) [inline src/components/20-molecules/datepicker/e2e.js:99]: Good!

File: src/components/20-molecules/datepicker/ui.test.js (hunk 10 above)
Comment (markus-walther) [reply src/components/20-molecules/datepicker/ui.test.js:693]: As agreed orally, we'll fix this in a separate issue; thus, for now this is OK here.

**Review by markus-walther — DISMISSED** [review]
Thomas,

LGTM.

Cheers, Markus

**Review by amir-ag — APPROVED** [review]
