### PR TITLE
set variable to a noop function

### LINKED ISSUE #2077: Carousel error: this.removeEventListenerAnimationEnd is not a function
Carousel version installed: `3.2.7`

Browser console reports a carousel error: `Uncaught TypeError: this.removeEventListenerAnimationEnd is not a function`

image

image

### PR DESCRIPTION
**Pull request by danyball**
Fixes #2077

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Modifications still work in IE.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

File: src/components/10-atoms/carousel/index.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ class AXACarousel extends InlineStyles {
     this.slides = null;
     this.visibleSlideIndex = 0;
     this.swiper = null;
-    this.removeEventListenerAnimationEnd = null;
+    this.removeEventListenerAnimationEnd = () => {};
```
Comment (markus-walther) [inline src/components/10-atoms/carousel/index.js:50]: Good!

**Review by markus-walther — DISMISSED** [review]
LGTM

**Review by markus-walther — APPROVED** [review]
