### PR TITLE
Bugfix/can use any constructor features

### LINKED ISSUE #747: Safari with-react and built-in styles not global
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All `<style>`s should be in `<head>`

## Actual Behavior

All `<style>` tags are multiple within the `wcNode`.

## Steps to Reproduce the Problem

1. https://github.com/axa-ch/patterns-library-examples/tree/master/react
2. `npm start`
3. open `http://localhost:3000` in Safari

screen shot 2018-12-05 at 20 46 04

## Specifications

 - Browser:
 - Browser Version:
 - Node Version:
 - NPM Version:
 - Platform:

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #747 

Changes proposed in this pull request:

 -
 -
 -

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/js/abstract/hocs/with-context.js [hunk 1]
```diff
@@ -6,6 +6,12 @@ const withContext = Base =>
    * Adds the ability to provide and consume contextual data.
    */
   class WithContext extends Base {
+    init(options) {
+      super.init(options);
+
+      // important: because of constructor caveats we have to override this lazily upon init
+      this._makeContextReady = this._makeContextReady.bind();
```
Comment (LucaMele) [inline src/js/abstract/hocs/with-context.js]: I saw this as well in my analysis

File: src/components/m-header-mobile-languages/index.js [hunk 2]
```diff
@@ -25,31 +25,31 @@ class AXAHeaderMobileLanguages extends BaseComponentGlobal {
 
   init() {
     super.init({ styles, template });
-  }
 
-  handleClick = (event) => {
-    const { target: { lang } } = event;
+    this.handleClick = (event) => {
```
Comment (LucaMele) [inline src/components/m-header-mobile-languages/index.js]: Yepp cool i saw this as well so i was going in the right direction :)
