### PR TITLE
Datepicker: fix value reset when confirming without day change

### LINKED ISSUE #620: Datepicker: value reset when confirming without day change
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

Datepicker has a date value. Then I open it's calendar and press "Confirm" to close the calendar. The previous date value should stay as was.

## Actual Behavior

Datepicker has a date value. Then I open it's calendar (may switch the month, but doesn't have to) and then press "Confirm" to close the calendar. The previous date **value is reset and "null" displays**.
A value of **false** is dispatched in the axa-change event.

## Steps to Reproduce the Problem

1. https://axa-ch.github.io/patterns-library/organisms.html#o-datepicker
2. choose a date in datepicker and press Confirm
3. open the calendar again and press Confirm without clicking on a day

image

(Related to #561)

### PR DESCRIPTION
**Pull request by MarekLacoAXA**
Without a day change (click on day) the m-datepicker-body doesn't have
a "value" attribute. It does have "day" attribute.
So this change uses the "day" attribute in case the "value" is falsy.

Fixes #620 .

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
 
 # How Has This Been Tested?
 
locally
 
 # Checklist:
 
 - [x] I have performed a self-review of my own code
 - [x] I have commented my code, particularly in hard-to-understand areas
 - [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/m-datepicker/js/datepicker.js [hunk 1]
```diff
@@ -89,7 +89,12 @@ export default class Datepicker {
     this.unOkButtonListenerEnd = on(this.wcNode.querySelector('.js-datepicker__button__Ok'), EVENTS.CLICK, () => {
       const year = this.datepickerBody.getAttribute('year');
       const month = this.datepickerBody.getAttribute('month');
-      const day = this.datepickerBody.getAttribute('value');
+      const dayAsValue = this.datepickerBody.getAttribute('value'); // new value - after click on a day
+      let dayAsDay = this.datepickerBody.getAttribute('day'); // prev value - prior click on a day
```
Comment (LucaMele) [inline src/components/m-datepicker/js/datepicker.js]: please use `js/get-attribute.js` helper to do this.

**Comment by LucaMele** [comment]
Please fix linting issue

bildschirmfoto 2018-10-23 um 09 53 19

File: src/components/m-datepicker/js/datepicker.js (hunk 1 above)
Comment (AndyOGo) [reply src/components/m-datepicker/js/datepicker.js]: hmh, why isn't `getAttribute` helper used?
