### PR TITLE
fix(built-in): added missing polyfills for IE11

### LINKED ISSUE #698: IE11 built-in Object expected
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

IE11 should succesfully render extended built-in elemets!

## Actual Behavior

IE11 doesn't render any extended built-in and instead throws:

```sh
SCRIPT5007: Object expected
File: app.js, Line: 1, Column: 15923
```

## Steps to Reproduce the Problem

1. Open IE 11
2. go to https://axa-ch.github.io/patterns-library/organisms.html#o-table

screen shot 2018-11-29 at 11 16 32

screen shot 2018-11-29 at 11 15 18

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #698 Blocked by #717 

Changes proposed in this pull request:

 - Adds needed `Object.*` polyfill for built-in polyfill in IE11

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/app/es6-polyfills.js [hunk 1]
```diff
@@ -4,6 +4,11 @@ import 'core-js/es6/reflect';
 import 'core-js/es6/promise';
 // IE11 does not support Array.from
 import 'core-js/fn/array/from';
+// IE11 does not support Object.* which is needed for built-in element polyfill
```
Comment (AndyOGo) [inline src/app/es6-polyfills.js]: It seems that Babel-Env does not defer needed polyfills from depenedencies 🤔

**Comment by AndyOGo** [comment]
IE11 works now, but is suuuuuuuper slow - long running script...

screen shot 2018-12-03 at 18 57 01
