### PR TITLE
Fix branch deployment

### LINKED ISSUE #2378: branch deployment script move plib-feature/develop assets
With branch deployment, the assets of the develop branch are moved to a newly generated feature branch instead of copying them from another source.

### PR DESCRIPTION
**Pull request by MKaHead**
Fixes #2378

Fixes
- In a feature branch deployment, the find method has also listed the develop assets and therefore these have been deleted.
Improvements
- Instead of mv something and moving back use copy.
- Script always tried to remove "." so excluded this as well.
- if cd dist not found exit script.

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

File: scripts/branch-deployment.sh [hunk 1]
```diff
@@ -55,7 +55,7 @@ ALL_FOLDERS_DEPTH_1=$(find . -maxdepth $MAX_DEPTH -not -path "./.*" -type d | cu
 '
 for x in $ALL_FOLDERS_DEPTH_1; do
     # If folder is no longer linked to a remote branch, remove it.
-    if [[ $ALL_BRANCHES != *"$x"* ]]; then
+    if [[ $ALL_BRANCHES != *"$x"* ]] && [[ "develop/favicons" != *"$x"* ]] && [[ "develop/fonts" != *"$x"* ]] && [[ "develop/images" != *"$x"* ]] && [[ "develop/icons" != *"$x"* ]]; then
```
Comment (markus-walther) [inline scripts/branch-deployment.sh]: Looks rather ugly...

File: scripts/branch-deployment.sh [hunk 2]
```diff
@@ -24,7 +24,7 @@ git clone https://$GITHUB_TOKEN@github.com/axa-ch-webhub-cloud/plib-feature.git
 
 rm -rf ./dist/$BRANCH_NAME/
 mkdir -p ./dist/$BRANCH_NAME
-mv -v ./storybook-static/* ./dist/$BRANCH_NAME/
+cp -R -v ./storybook-static/* ./dist/$BRANCH_NAME/
```
Comment (markus-walther) [inline scripts/branch-deployment.sh:27]: Why is this better/solving a previous problem? You may want to comment the shell script with hash comments line-by-line....

**Review by markus-walther — COMMENTED** [review]
Hi,

some comments on your ongoing work!

Cheers, Markus

File: scripts/branch-deployment.sh (hunk 1 above)
Comment (MKaHead) [reply scripts/branch-deployment.sh]: now fixed in find command, only added "." because will be static

File: scripts/branch-deployment.sh (hunk 2 above)
Comment (MKaHead) [reply scripts/branch-deployment.sh:27]: Instead of mv something and moving back use copy

Comment (markus-walther) [reply scripts/branch-deployment.sh:27]: I see, makes sense!

File: scripts/branch-deployment.sh [hunk 3]
```diff
@@ -24,19 +24,19 @@ git clone https://$GITHUB_TOKEN@github.com/axa-ch-webhub-cloud/plib-feature.git
...
 
 # Done! From here, everything would be ready to be committed and pushed. But
 # outdated branches need to be cleaned up too, so...
 
 # List only remote branches
 ALL_BRANCHES=$(git --no-pager branch -a -r)
 
-cd ./dist
+cd ./dist || exit
```
Comment (markus-walther) [inline scripts/branch-deployment.sh:35]: defensive programming - good!

File: scripts/branch-deployment.sh [hunk 4]
```diff
@@ -24,19 +24,19 @@ git clone https://$GITHUB_TOKEN@github.com/axa-ch-webhub-cloud/plib-feature.git
...
 
-# Find all folders for 2 levels down, ignore .git folder and cut './' at the beginning of each folder
+# Find all folders for 2 levels down, ignore .git folder and develop assets. Then cut './' at the beginning of each folder
```
Comment (markus-walther) [inline scripts/branch-deployment.sh:37]: Hey, *now* it's readable ;-)

**Review by markus-walther — APPROVED** [review]
Hi Marco,

now it LGTM!
Good work!!

--M.
