### PR TITLE
fix FF issue

### LINKED ISSUE #77: Firefox: TypeError: window.customElements is undefined
> TypeError: window.customElements is undefined

screen shot 2017-12-18 at 11 20 19

### PR DESCRIPTION
**Pull request by LucaMele**
fixes #77

### CODE REVIEW

File: src/components/a-device-state/js/device-state.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { publish, subscribe } from '../../../js/pubsub';
 const deviceStateClass = '.a-device-state';
 const reWhiteSpace = /\s/g;
 const reUnquote = /^"+|"+$/g;
-let isDomReady = false;
+let iswcdomready = false;
```
Comment (AndyOGo) [inline src/components/a-device-state/js/device-state.js]: This one does not add a custom component, hence domready is sufficient.
