### PR TITLE
Fix uncontrolled use under React in Storybook and inappropriate :hover styles on touch devices

### LINKED ISSUE #1707: Checkbox React Example not working
https://patterns.axa.ch/?path=/story/components-atoms-checkbox-react--checkbox-uncontrolled

You cant unselect checkbox in this example. If you deselect "checked" knobs it works.

### LINKED ISSUE #1709: Checkbox: mobil/touch: "uncheck" not possible
Repro:
- chrome in "mobile" mode
- tap the checkbox
- "checked" seems to stay
- tap anywhere else: checkbox is unchecked

I think the hover effect doesnt go away.

### LINKED ISSUE #1711: Checkbox: Child label not vertically centerd
image

### PR DESCRIPTION
**Pull request by markus-walther**
Fixes #1707.
Fixes #1709.
Fixes #1711.

### CODE REVIEW

File: src/components/10-atoms/checkbox/react/story.jsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ storiesOf('Components|Atoms/Checkbox/React', module)
       'checkmark',
       'checkmark-inverted',
     ]);
-    const checked = boolean('checked', true);
+
```
Comment (danyball) [inline src/components/10-atoms/checkbox/react/story.jsx]: What about to show that knob, but with your statement that this knob do not make sense here?!

**Review by danyball — DISMISSED** [review]

**Review by LucaMele — DISMISSED** [review]
lgtm

File: src/components/10-atoms/checkbox/react/story.jsx (hunk 1 above)
Comment (markus-walther) [reply src/components/10-atoms/checkbox/react/story.jsx]: The knob is deleted, the diff is red....

Comment (danyball) [reply src/components/10-atoms/checkbox/react/story.jsx]: Yes. That the users are not confused that this knob is missing here (and at the "normal" story it is not) we could tell them that is it deactivated in this case. And why.

File: src/components/10-atoms/checkbox/index.scss [hunk 2]
```diff
@@ -36,7 +36,7 @@ axa-checkbox {
     overflow: hidden;
   }
 
-  .a-checkbox__input {
+  .a-checkbox__input.a-checkbox__input {
```
Comment (danyball) [inline src/components/10-atoms/checkbox/index.scss:39]: You doubled that class because of specificity?

File: src/components/10-atoms/checkbox/index.scss [hunk 3]
```diff
@@ -168,41 +168,41 @@ axa-checkbox {
...
       @include typo(primary, small-1);
 
       @include breakpoint($mediaquery-md-up) {
          @include typo(primary, medium);
       }
-    }
+  }
 
-    &:hover {
+  &:hover.no-touch {
```
Comment (danyball) [inline src/components/10-atoms/checkbox/index.scss]: On touch devices there is no hover effect anymore. nice. 

But the bug still exists (on https://axa-ch.github.io/plib-feature/bugfix/checkbox-uncontrolled/?path=/story/components-atoms-checkbox--checkbox ):
**EDIT: The problem could be, that this feature branch deploy is too old. I saw that azure was failing.**

If you tap on a checked checkbox, there is thas small square inside the checkbox:
image

Comment (danyball) [reply src/components/10-atoms/checkbox/index.scss]: Dont know why, but this rule is active:
image

**Review by danyball — CHANGES_REQUESTED** [review]
Azure is failing.

File: src/components/10-atoms/checkbox/index.scss (hunk 2 above)
Comment (markus-walther) [reply src/components/10-atoms/checkbox/index.scss:39]: yes, exactly!

File: src/components/10-atoms/checkbox/index.scss (hunk 3 above)
Comment (markus-walther) [reply src/components/10-atoms/checkbox/index.scss]: I think this is all due to feature-branch problems, and/or not using a real mobile device. Using a local server and real Android phone with Chrome, everything seems to work.

**Review by danyball — DISMISSED** [review]
LGTM. Have found another minor - would suggest to release this branch first if fix of https://github.com/axa-ch/patterns-library/issues/1711 is not a small one.

**Review by danyball — DISMISSED** [review]
