### PR TITLE
Bugfix/2078 button key

### LINKED ISSUE #2078: AXAButton of type submit doesn't submit form on Enter keypress
@axa-ch/button v6.0.8

If AXAButton of type submit inside of form is focused using Tab key and then Enter is pressed submit event on form is not triggered.

## Expected Behavior
Enter key press on focused submit button should submit the form.

## Current Behavior
Enter key press on button does not submit the form.

## Reproduction
https://codesandbox.io/s/agitated-haibt-b1h2p?file=/src/App.js

### LINKED ISSUE #2085: Button: focused UX wrong
Keyboard focus should have same effect like mouse hover.
see https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=225%3A240

- Button
- button-link

There should not be an outline:

image

### PR DESCRIPTION
**Pull request by danyball**
Fixes #2078 
Fixes #2085 

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Modifications still work in IE. --> @salle18 said, they do not need IE11 support for the "submit keyboard" bug.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

File: src/components/10-atoms/button/index.js [hunk 1]
```diff
@@ -21,10 +21,6 @@ const isNativeShadowDOM = (window || global).ShadowRoot
   : false;
 /* eslint-enable no-undef */
 
-// @TODO: REMOVE ONCE IE11 is deprecated!!!!
```
Comment (raphaellueckl) [inline src/components/10-atoms/button/index.js]: Why did you remove that? We still need to support IE11

File: src/components/10-atoms/button/pw.ui.test.js [hunk 2]
```diff
@@ -1,11 +1,30 @@
...
+
+    const axaButton = await page.$(axaButtonSelector);
+    const getAxaButtonText = () => page.textContent(axaButtonSelector);
+
+    expect(await getAxaButtonText()).toContain('0');
+
+    await axaButton.click();
+    expect(await getAxaButtonText()).toContain('1');
+
+    await axaButton.click();
```
Comment (raphaellueckl) [inline src/components/10-atoms/button/pw.ui.test.js:27]: Could be necessary, but is it really (I noticed that this was ported from testcafe)? To do this two times instead of just once? Because If not needed, stuff like that just unnecessarily bloats the test for no benefit. You already checked if the axa button text did update, why do you check another time?

File: src/components/10-atoms/input-text/pw.ui.test.js [hunk 3]
```diff
@@ -0,0 +1,25 @@
+const host = process.env.TEST_HOST_STORYBOOK_URL;
+
+describe('input-text', () => {
```
Comment (raphaellueckl) [inline src/components/10-atoms/input-text/pw.ui.test.js]: In other input-text testcafe test, this describe starts with: `Input text` instead of `input-text`, although we do not have a common ground here anyways, I recommend to stick to what we have.

File: src/components/20-molecules/datepicker/pw.ui.test.js [hunk 4]
```diff
@@ -0,0 +1,57 @@
+const host = process.env.TEST_HOST_STORYBOOK_URL;
+
+describe('Datepicker', () => {
```
Comment (raphaellueckl) [inline src/components/20-molecules/datepicker/pw.ui.test.js:3]: I really like your effort to migrate over to playwright! Nice!

**Review by raphaellueckl — CHANGES_REQUESTED** [review]
Special thanks to your testcafe migration effort! Very nice!!

File: src/components/10-atoms/button/index.js (hunk 1 above)
Comment (danyball) [reply src/components/10-atoms/button/index.js]: And it still works with IE. Dont know why we have that specail function for that.

File: src/components/10-atoms/button/pw.ui.test.js (hunk 2 above)
Comment (danyball) [reply src/components/10-atoms/button/pw.ui.test.js:27]: Just migrated that. Dont know why.

File: src/components/20-molecules/datepicker/pw.ui.test.js (hunk 4 above)
Comment (danyball) [reply src/components/20-molecules/datepicker/pw.ui.test.js:3]: Have to:) Testcafe tests are broken.

File: src/components/10-atoms/button/index.js (hunk 1 above)
Comment (raphaellueckl) [reply src/components/10-atoms/button/index.js]: This needs to be tested on AEM. It looks like it was implemented to circumvent a problem in combination with aem component.

File: src/components/20-molecules/datepicker/pw.ui.test.js (hunk 4 above)
Comment (markus-walther) [reply src/components/20-molecules/datepicker/pw.ui.test.js:3]: I do like your efforts, too - but I don't like that you are doing it in a PR that is totally unrelated.

I wrote a document on traceability of PL changes, and this would adversely affect it. You are fixing 2 button issues here - other issues should be separated out into a properly named separate PR.

Comment (danyball) [reply src/components/20-molecules/datepicker/pw.ui.test.js:3]: Just look closer to the tests i have migrated. The tests are clicking on a axa-button to do something. And my change is that the button only accepts click events which are `isTrusted`. And testcafe generates synthetic events which are isTrusted=false. Thats why i have to fix/migrate failing tests.

File: src/components/10-atoms/button/index.js (hunk 1 above)
Comment (danyball) [reply src/components/10-atoms/button/index.js]: Good point. We should test that on AEM - do you have an idea how?

Comment (raphaellueckl) [reply src/components/10-atoms/button/index.js]: publish a beta version of pod-aem-pattern-library with a beta version of button.

.... or just readd this code 😅  IE11 will be deprecated this year. We could just wait for then and remove it laster imho.

Comment (danyball) [reply src/components/10-atoms/button/index.js]: :D but this code is buggy. I have to change it to fix the form-bug. I will check if its possible to test at AEM with IE.

Comment (danyball) [reply src/components/10-atoms/button/index.js]: Have tested the button on AEM with chrome and IE11 on my local machine. Working!

image
You can see the formular which i used and the fact that i can navigate to page 2 of the formular.

File: src/components/10-atoms/button/index.js [hunk 5]
```diff
@@ -145,7 +141,7 @@ class AXAButton extends InlineStyles {
     // form behaviour works (submit, reset, etc). The reason why it works with fake button is
     // that fake button is NOT inside a ShadowDOM. The event instead
     // bubbles out of ShadowDOM, hence the stop propagation trick
-    if (eventIsTrusted(e) && isNativeShadowDOM && this.isTypeSubmitOrReset) {
+    if (e.isTrusted && isNativeShadowDOM && this.isTypeSubmitOrReset) {
```
Comment (raphaellueckl) [inline src/components/10-atoms/button/index.js]:
```
// IF statement that can be removed with IE11 support dropping
if (document.documentMode && eventIsTrusted(e) && isNativeShadowDOM && this.isTypeSubmitOrReset) {
  // duplicated code, that will be removed with ie11 support fading out
} else if (e.isTrusted && isNativeShadowDOM && this.isTypeSubmitOrReset) {
  //... if-body
}
```

Comment (danyball) [reply src/components/10-atoms/button/index.js]: done (the submit bug is not relevant for ie11)

**Review by raphaellueckl — DISMISSED** [review]

File: src/components/10-atoms/button/index.js [hunk 6]
```diff
@@ -145,7 +145,17 @@ class AXAButton extends InlineStyles {
...
-    if (eventIsTrusted(e) && isNativeShadowDOM && this.isTypeSubmitOrReset) {
+
+    // IF statement that can be removed with IE11 support dropping
+    if (
+      document.documentMode &&
+      eventIsTrusted(e) &&
+      isNativeShadowDOM &&
+      this.isTypeSubmitOrReset
+    ) {
+      e.stopPropagation();
```
Comment (markus-walther) [inline src/components/10-atoms/button/index.js]: DRY violation: the `if/else if` bodies have the same content, hence can be merged. Suggestion: make two named conditions `const isIESubmitResetEvent = ` and similar then do `if (isIESubmitResetEvent || isSubmitResetEvent) {...`

**Review by markus-walther — CHANGES_REQUESTED** [review]
Hi Dani, almost there!

One small thing left, in my view...

Cheers, Markus

File: src/components/10-atoms/button/index.js [hunk 7]
```diff
@@ -145,7 +145,17 @@ class AXAButton extends InlineStyles {
...
+    // TODO: remove all the IE stuff if support drops
+    const isIESubmitResetEvent =
+      document.documentMode &&
+      eventIsTrusted(e) &&
+      isNativeShadowDOM &&
+      this.isTypeSubmitOrReset;
+    const isSubmitResetEvent =
+      e.isTrusted && isNativeShadowDOM && this.isTypeSubmitOrReset;
+
+    if (isIESubmitResetEvent || isSubmitResetEvent) {
```
Comment (markus-walther) [inline src/components/10-atoms/button/index.js:158]: wonderful!

**Review by markus-walther — APPROVED** [review]
LGTM

**Review by raphaellueckl — APPROVED** [review]
