### PR TITLE
Fix axa-footer delayed-children problem

### LINKED ISSUE #1890: axa-footer sometimes does not style its children correctly
Suppose axa-footer is used natively. Also suppose that the defining JavaScript _dist_ bundle is loaded and evaluated prior to the occurrence of a `<axa-footer>` tag with its slotted children.

In this situation, the browser's HTML parser, upon encountering the opening `<axa-footer>` tag, may immediately construct the element and also render it.

At this point in time its children are not yet in the DOM tree.

As a result the visual rendering of this component is wrong.

Fix this, and properly accomodate all possible construction orders of the component vs its children.

Reproduction: https://codepen.io/tsaadaasmarino/pen/VweqVJa

### PR DESCRIPTION
**Pull request by markus-walther**
Fixes #1890.

Tested by simple HTML page consisting of **inline script** with dist export, followed by axa-footer with lots of children.
It is hypothesized that an inline script is going to be loaded **and** evaluated much faster than a network-loaded (i.e. `src`) script, which is why the subtle bug mentioned in #1890 deterministically occurs in this scenario, and only if the script is first in textual order.

The bigger task of making the entire footer children dynamically updateable has to wait for another day, as the convoluted implementation makes a simple modification towards supporting this scenario difficult to implement for now.

# Done is when (DoD):
- [x] Modifications within components are reflected by tests.
- [x] A self-review of the code has been performed.
- [x] The modified component properties have been added to the typescript typings.
- [x] Potential design changes have been reviewed by a designer.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [x] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [x] The modifications are shortly added to CHANGELOG.md with the issue number.
- [x] The modifications still work in IE.
- [x] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

### CODE REVIEW

File: src/components/30-organisms/footer/index.js [hunk 1]
```diff
@@ -85,13 +84,13 @@ class AXAFooter extends InlineStyles {
   }
 
   /**
-   * A slot element needs to be a direct child of a webcomponent. Since AEM
+   * A slot element needs to be a direct child of a web component. Since AEM
```
Comment (01231) [inline src/components/30-organisms/footer/index.js:87]: thanks for cleaning up all comments👍🏼

File: src/components/30-organisms/footer/index.js [hunk 2]
```diff
@@ -361,6 +378,12 @@ class AXAFooter extends InlineStyles {
       }
     }
   };
+
+  disconnectedCallback() {
```
Comment (01231) [inline src/components/30-organisms/footer/index.js:382]: nice

**Review by 01231 — DISMISSED** [review]
Tested and works!
