### PR TITLE
Bugfix/some dropdown issues

### LINKED ISSUE #623: Dropdown component - attribute value does not select option in native mode.
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

When value is set to the dropdown corresponding option should be selected by default.

## Actual Behavior

Value set is ignored in **"native"** mode only.

## Steps to Reproduce the Problem

1.
screen shot 2018-10-22 at 1 43 53 pm

2.
screen shot 2018-10-22 at 1 43 25 pm

3.
screen shot 2018-10-22 at 1 43 17 pm

## Specifications
Operating system OS X 10.13.5
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2247 x 1063
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

### PR DESCRIPTION
**Pull request by LucaMele**
Fixes #623 #624 #625 #626.

### CODE REVIEW

File: src/js/to-prop.js [hunk 1]
```diff
@@ -1,16 +1,63 @@
...
 
+/**
+ * Try to parse a string value by analsing its type and find the best fitting behaviour.
+ *
+ * @param {String} value - The string to parse.
+ * @param {String} [name] - Normally an attribute's name.
+ * @param {String} [type] - What tipe is passed. If none is set, behave as HTML SPEC.
+ * @returns {*} - Returns the value of the string - in case of valid JSON the result of `JSON.parse` else plain text.
+ */
+function toTypedProp(value, name, type) {
```
Comment (AndyOGo) [inline src/js/to-prop.js]: type checking ftw

File: src/js/get-attribute.js [hunk 2]
```diff
@@ -1,15 +1,20 @@
...
  * @returns {*} - Returns the value of the attribute - in case of valid JSON the result of `JSON.parse` else plain text.
  */
-function getAttribute(node, name) {
-  if (typeof node.hasAttribute === 'function' && !node.hasAttribute(name)) {
+function getAttribute(node, name, type) {
+  let derivedType = type;
+  const isElementNode = node.nodeType === 1;
+
+  if (isElementNode && !node.hasAttribute(name)) {
     return false;
```
Comment (AndyOGo) [inline src/js/get-attribute.js]: @LucaMele 
I just saw this, we return `false` if an attribute does not exists, though this should only be the case for `PropTypes.bool` 💣 
All others should be `undefined` 🤔
