### PR TITLE
Native dropdown numbers as values selection fixed.

### LINKED ISSUE #688: Dropdown: native selection not working with numbers as values
## Are you reporting a bug or a feature?

 - [x] Bug

## Expected Behavior

When I select item from a native dropdown that has number as value it is not selected correctly.

## Steps to Reproduce the Problem

 - Add the items attribute in which the values are set as numbers.
`items='[{"name": "Item 1 empty value", "url": "#", "value":3}, {"name": "Item 2", "url": "#", "value":4}, {"name": "Item 3", "url": "#", "value":5}]'`

 - Select item from the list.
The value will be set but the dropdown will not show the selection.

nov-26-2018 15-51-09

### PR DESCRIPTION
**Pull request by nakovskijosif**
Fixes #688 .

Changes proposed in this pull request:

fixed the comparison between different prop types.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/m-dropdown/_template.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ const nativeSelect = ({ title, items, size, value }) => html`<div class="${class
       items.map(({ name, value: itemValue, url }, index) => {
         const _itemValue = getItemValue(itemValue, index);
         return html`<option value="${_itemValue}" data-url="${url}" ${
-          _itemValue === value ? 'selected' : ''
+          `${_itemValue}` === `${value}` ? 'selected' : ''
```
Comment (AndyOGo) [inline src/components/m-dropdown/_template.js]: Guess this check should not be of strict type?
If so I would just write `_itemValue  == value`, the javascript engine will handle type conversion for you, so that stuff like `'4' == 4` will be truthy

Comment (nakovskijosif) [reply src/components/m-dropdown/_template.js]: I can do that, will need to add  // eslint-disable-line though.

Comment (LucaMele) [reply src/components/m-dropdown/_template.js]: NO PLEASE nogo for `_itemValue == value` from my side. Better type conversion to string so that we are type save. @nakovskijosif

Comment (nakovskijosif) [reply src/components/m-dropdown/_template.js]: I will revert my last commit in a sec.

Comment (AndyOGo) [reply src/components/m-dropdown/_template.js]: I agree with you Luca, not many people read specs and definitely saver to stick with `===` than `==`. My point here is that this is perfect valid example of a `==` use case.

But to make this point more prevalent, we could also use `toString` conversion helpers, instead of meaning-lesl template lits

Comment (LucaMele) [reply src/components/m-dropdown/_template.js]: ok with the toString. For me is the same as both clearly show what is happening.
