### PR TITLE
Fix remove of style height

### LINKED ISSUE #2312: Accordion: Automatically resize the Accordion if the content changes.
In SPAs (Single Page Application). The content of the 'Accordion' might dynamically change based on user input or async data fetching.

At the moment 'Accordion' does not dynamically resize if the content changes. So if the height of the content increases the 'Accordion' does not show all the content.

Possible use-cases:
- async loading / rendering of data after the Accordion is opended
- content added to Accordion based on user actions
- Accordion inside Accordion (mind-blowing ;-) )

Proposed implementation: Use an implementation based on ResizeObserver.

We have implemented a workaround for this in https://github.axa.com/avengers/bra-frontend (AccordionDynamic) that is dependent on implementation details of 'Accordion'.

Best regards

### PR DESCRIPTION
**Pull request by MKaHead**
Fixes #2312 accordion content

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

File: src/components/20-molecules/accordion/index.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ const expandContent = el => {
 
   const expandAnimation = () => {
     // remove "height" from the element's inline styles, so it can return to its initial value
-    delete el.style.height;
+    el.style.removeProperty('height');
```
Comment (markus-walther) [inline src/components/20-molecules/accordion/index.js:44]: Good!

**Review by markus-walther — APPROVED** [review]
Marco,

LGTM!

Cheers, Markus
