### PR TITLE
fix axa link external attribute not opening in new tab

### LINKED ISSUE #1746: axa-link 'external' property doesn't seem to work anymore
Feedback from @MKaHead 

Reproduce: https://patterns.axa.ch/iframe.html?id=components-atoms-link--link&knob-link=https://www.axa.ch/en/information/data-protection.html&knob-Link%20text=Data%20protection%20statement&knob-external=true&knob-variant=&knob-icon=&knob-Background%20color=white

### PR DESCRIPTION
**Pull request by raphaellueckl**
Fixes #1746

There is no Test of the functionality, because of this comment: https://stackoverflow.com/a/56396445/2311557

I hope that puppeteer will help us here.

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [x] A self-review of the code has been performed.
- [x] The modified component properties have been added to the typescript typings.
- [x] Potential design changes have been reviewed by a designer.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [x] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [x] The modifications are shortly added to CHANGELOG.md with the issue number.
- [x] The modifications still work in IE.
- [x] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

### CODE REVIEW

File: src/components/10-atoms/link/index.js [hunk 1]
```diff
@@ -80,7 +80,7 @@ class AXALink extends LitElement {
           if (typeof this.onClick === 'function') {
             this.onClick();
           } else {
-            window.location.href = this.href;
+            window.open(this.href, this.external ? '_blank' : '_top');
           }
         }}"
         target="${this.external ? '_blank' : '_top'}"
```
Comment (danyball) [inline src/components/10-atoms/link/index.js]: This line seems to be obsolet now. I think every browser can handle window.open and target is not a "must" for a tag.

**Review by danyball — DISMISSED** [review]

File: src/components/10-atoms/link/index.js (hunk 1 above)
Comment (raphaellueckl) [reply src/components/10-atoms/link/index.js]: Right, but I left it there to make the intent of the link obvious. Maybe this helps a screenreader or something.

Comment (LucaMele) [reply src/components/10-atoms/link/index.js]: I would leave it in case we refactor the JS or in case the JS is not working, better to have it as HTML as well

**Review by markus-walther — APPROVED** [review]
Very nice, works also if after 1 x render JS is deactivated.
